version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "9091:9091"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9091/api