apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-emt-app-statefulset-0
  namespace: emt-app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
