name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Push Backend Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker build -t miabosheva/project-emt-backend:latest ./backend
        docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
        docker push miabosheva/project-emt-backend:latest

    - name: Build and Push Frontend Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker build -t miabosheva/project-emt-frontend:latest ./frontend
        docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
        docker push miabosheva/project-emt-frontend:latest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          kubectl config set-context k3d-emt-app-cluster --cluster=k3d-emt-app-cluster --user=admin@k3d-emt-app-cluster
          kubectl config use-context k3d-emt-app-cluster
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f EMT-project/kubernetes/deployment.yaml
          kubectl wait --for=condition=available --timeout=300s deployment/emt-app-deployment

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Set up kubectl
  #     uses: azure/k8s-set-context@v1
  #     with:
  #       method: kubeconfig
  #       kubeconfig: ${{ secrets.KUBE_CONFIG }}
  #       context: k3d-emt-app-cluster
  #   # - name: Debug Information
  #   #   run: |
  #   #     pwd
  #   #     ls -R
  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f EMT-project/kubernetes/deployment.yaml