name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: "main"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: miabosheva/project-emt-backend:latest

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: miabosheva/project-emt-frontend:latest
  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #   - name: Set up kubectl
  #     uses: azure/k8s-set-context@v1
  #     with:
  #       method: kubeconfig
  #       kubeconfig: ${{ secrets.KUBE_CONFIG }}
  #       context: your-kubernetes-context #replace

  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f kubernetes/deployment.yaml